In [2]:
import pandas as pd
import pickle
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [3]:
data = pd.read_csv(r"C:\Users\monik\OneDrive\Desktop\burnout prediction\dataset\StressLevelDataset.csv")

In [4]:
X = data.drop("stress_level", axis=1)
y = data["stress_level"]

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [6]:
model = RandomForestClassifier()
model.fit(X_train, y_train)

RandomForestClassifier()

In [7]:
pickle.dump(model, open("model.pkl", "wb"))

In [8]:
print("Model trained and saved!")

Model trained and saved!

In [2]:
import pandas as pd

In [4]:
import numpy as np

In [5]:
df = pd.read_csv("StressLevelDataset.csv")
df.head()

,anxiety_level,self_esteem,mental_health_history,depression,headache,blood_pressure,sleep_quality,breathing_problem,noise_level,living_conditions,...,basic_needs,academic_performance,study_load,teacher_student_relationship,future_career_concerns,social_support,peer_pressure,extracurricular_activities,bullying,stress_level
0,14,20,0,11,2,1,2,4,2,3,...,2,3,2,3,3,2,3,3,2,1
1,15,8,1,15,5,3,1,4,3,1,...,2,1,4,1,5,1,4,5,5,2
2,12,18,1,14,2,1,2,2,2,2,...,2,2,3,3,2,2,3,2,2,1
3,16,12,1,15,4,3,1,3,4,2,...,2,2,4,1,4,1,4,4,5,2
4,16,28,0,7,2,3,5,1,3,2,...,3,4,3,1,2,1,5,0,5,1

In [6]:
selected_columns = [
    "anxiety_level",
    "self_esteem",
    "mental_health_history",
    "depression",
    "sleep_quality",
    "academic_performance",
    "study_load",
    "future_career_concerns",
    "social_support",
    "peer_pressure",
    "stress_level"
]

df = df[selected_columns]
df.head()

,anxiety_level,self_esteem,mental_health_history,depression,sleep_quality,academic_performance,study_load,future_career_concerns,social_support,peer_pressure,stress_level
0,14,20,0,11,2,3,2,3,2,3,1
1,15,8,1,15,1,1,4,5,1,4,2
2,12,18,1,14,2,2,3,2,2,3,1
3,16,12,1,15,1,2,4,4,1,4,2
4,16,28,0,7,5,4,3,2,1,5,1

In [7]:
X = df.drop("stress_level", axis=1)
y = df["stress_level"]

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [9]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()

model.fit(X_train, y_train)

RandomForestClassifier()

In [10]:
from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.8818181818181818

In [11]:
import pickle

pickle.dump(model, open("model.pkl", "wb"))

In [ ]:
import pandas as pd

df = pd.read_csv("StressLevelDataset.csv")

selected_columns = [
    "anxiety_level",
    "self_esteem",
    "mental_health_history",
    "depression",
    "sleep_quality",
    "academic_performance",
    "study_load",
    "future_career_concerns",
    "social_support",
    "peer_pressure",
    "stress_level"
]

df = df[selected_columns]

In [2]:
import pickle

model = pickle.load(open("model.pkl", "rb"))

In [4]:
import pandas as pd

test_data = pd.DataFrame([{
"anxiety_level":5,
"self_esteem":1,
"mental_health_history":1,
"depression":5,
"sleep_quality":1,
"academic_performance":2,
"study_load":5,
"future_career_concerns":5,
"social_support":1,
"peer_pressure":5
}])

prediction = model.predict(test_data)

print("Prediction:", prediction)

Prediction: [2]

In [6]:
import pandas as pd

input_df = pd.DataFrame([{
"anxiety_level":5,
"self_esteem":1,
"mental_health_history":1,
"depression":5,
"sleep_quality":1,
"academic_performance":2,
"study_load":5,
"future_career_concerns":5,
"social_support":1,
"peer_pressure":5
}])

In [7]:
prediction = model.predict(input_df)

print("Prediction:", prediction)

Prediction: [2]

In [9]:
import pandas as pd

df = pd.read_csv("StressLevelDataset.csv")

In [10]:
df["stress_level"].value_counts()

stress_level
0    373
2    369
1    358
Name: count, dtype: int64

In [13]:
import pandas as pd

df = pd.read_csv("StressLevelDataset.csv")

df.head()

,anxiety_level,self_esteem,mental_health_history,depression,headache,blood_pressure,sleep_quality,breathing_problem,noise_level,living_conditions,...,basic_needs,academic_performance,study_load,teacher_student_relationship,future_career_concerns,social_support,peer_pressure,extracurricular_activities,bullying,stress_level
0,14,20,0,11,2,1,2,4,2,3,...,2,3,2,3,3,2,3,3,2,1
1,15,8,1,15,5,3,1,4,3,1,...,2,1,4,1,5,1,4,5,5,2
2,12,18,1,14,2,1,2,2,2,2,...,2,2,3,3,2,2,3,2,2,1
3,16,12,1,15,4,3,1,3,4,2,...,2,2,4,1,4,1,4,4,5,2
4,16,28,0,7,2,3,5,1,3,2,...,3,4,3,1,2,1,5,0,5,1

In [14]:
features = [
"anxiety_level",
"self_esteem",
"mental_health_history",
"depression",
"sleep_quality",
"academic_performance",
"study_load",
"future_career_concerns",
"social_support",
"peer_pressure"
]

X = df[features]
y = df["stress_level"]

In [15]:
print(X.columns)

Index(['anxiety_level', 'self_esteem', 'mental_health_history', 'depression',
       'sleep_quality', 'academic_performance', 'study_load',
       'future_career_concerns', 'social_support', 'peer_pressure'],
      dtype='str')

In [16]:
import pickle
import numpy as np

model = pickle.load(open("model.pkl","rb"))

tests = [
[1,4,0,1,4,4,2,2,4,1],   # expected low stress
[3,3,1,3,3,3,3,3,3,3],   # expected moderate stress
[5,1,1,5,1,2,5,5,1,5]    # expected high stress
]

print(model.predict(tests))

[2 1 2]

c:\Users\monik\OneDrive\Desktop\bp\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [17]:
import pandas as pd

importance = model.feature_importances_

feature_importance = pd.Series(importance, index=X.columns)
print(feature_importance.sort_values(ascending=False))

sleep_quality             0.188369
anxiety_level             0.167938
future_career_concerns    0.144544
depression                0.111752
academic_performance      0.106215
social_support            0.084619
peer_pressure             0.078347
self_esteem               0.071098
study_load                0.037268
mental_health_history     0.009850
dtype: float64

In [18]:
df["sleep_quality"].describe()

count    1100.000000
mean        2.660000
std         1.548383
min         0.000000
25%         1.000000
50%         2.500000
75%         4.000000
max         5.000000
Name: sleep_quality, dtype: float64

In [19]:
df.groupby("stress_level")["sleep_quality"].mean()

stress_level
0    4.126005
1    2.530726
2    1.303523
Name: sleep_quality, dtype: float64

In [21]:
import pandas as pd
import pickle
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [22]:
df = pd.read_csv("StressLevelDataset.csv")

In [23]:
df.head()

,anxiety_level,self_esteem,mental_health_history,depression,headache,blood_pressure,sleep_quality,breathing_problem,noise_level,living_conditions,...,basic_needs,academic_performance,study_load,teacher_student_relationship,future_career_concerns,social_support,peer_pressure,extracurricular_activities,bullying,stress_level
0,14,20,0,11,2,1,2,4,2,3,...,2,3,2,3,3,2,3,3,2,1
1,15,8,1,15,5,3,1,4,3,1,...,2,1,4,1,5,1,4,5,5,2
2,12,18,1,14,2,1,2,2,2,2,...,2,2,3,3,2,2,3,2,2,1
3,16,12,1,15,4,3,1,3,4,2,...,2,2,4,1,4,1,4,4,5,2
4,16,28,0,7,2,3,5,1,3,2,...,3,4,3,1,2,1,5,0,5,1

In [24]:
features = [
"anxiety_level",
"self_esteem",
"mental_health_history",
"depression",
"sleep_quality",
"academic_performance",
"study_load",
"future_career_concerns",
"social_support",
"peer_pressure"
]

X = df[features]
y = df["stress_level"]

In [25]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [26]:
model = RandomForestClassifier(
    n_estimators=300,
    max_depth=12,
    min_samples_split=5,
    random_state=42
)

model.fit(X_train, y_train)

RandomForestClassifier(max_depth=12, min_samples_split=5, n_estimators=300,
                       random_state=42)

In [27]:
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.8818181818181818

In [28]:
pickle.dump(model, open("model.pkl", "wb"))

In [29]:
tests = [
[1,4,0,1,4,4,2,2,4,1],
[3,3,1,3,3,3,3,3,3,3],
[5,1,1,5,1,2,5,5,1,5]
]

print(model.predict(tests))

[0 1 0]

c:\Users\monik\OneDrive\Desktop\bp\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [30]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=500,
    max_depth=15,
    min_samples_split=4,
    class_weight="balanced",
    random_state=42
)

In [31]:
model.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', max_depth=15,
                       min_samples_split=4, n_estimators=500, random_state=42)

In [32]:
from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.8863636363636364

In [33]:
import pickle
pickle.dump(model, open("model.pkl","wb"))

In [34]:
tests = [
[1,4,0,1,4,4,2,2,4,1],
[3,3,1,3,3,3,3,3,3,3],
[5,1,1,5,1,2,5,5,1,5]
]

print(model.predict(tests))

[0 1 2]

c:\Users\monik\OneDrive\Desktop\bp\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [35]:
from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Model Accuracy:", accuracy)

Model Accuracy: 0.8863636363636364

In [36]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[69  3  4]
 [ 5 65  3]
 [ 5  5 61]]

In [37]:
import pickle

pickle.dump(model, open("model.pkl", "wb"))

In [38]:
tests = [
[1,4,0,1,4,4,2,2,4,1],
[3,3,1,3,3,3,3,3,3,3],
[5,1,1,5,1,2,5,5,1,5]
]

print(model.predict(tests))

[0 1 2]

c:\Users\monik\OneDrive\Desktop\bp\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(